version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 research_rec.wsgi:application
    volumes:
      - .:/research_rec
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
